language: cpp

dist: xenial

matrix:
  fast_finish: true
  include:

    - os: linux
      compiler: clang  

    - os: linux
      compiler: g++
      env: 
        - COVERAGE
      addons:
        sonarcloud:
          organization: "mualphaomegaepsilon-github"

    - os: osx

    - os: windows

script:
  - if [ -n "${COVERAGE}" ]; then ./tests/shellcheck.sh; fi
  - if [ -n "${COVERAGE}" ]; then sudo rm /usr/bin/gcov && sudo ln -s /usr/bin/gcov-5 /usr/bin/gcov; fi
  - ./tests/setup.sh
  - ./tests/build.sh
  - ./tests/run.sh
  - if [ -n "${COVERAGE}" ]; then bash <(curl -s https://codecov.io/bash); fi
  - if [ -n "${SONAR_SCANNER_HOME}" ]; then sonar-scanner; fi
