language: cpp

dist: xenial
sudo: false

matrix:
  include:

    - os: linux
      compiler: clang  

    - os: linux
      compiler: g++
      env: 
        - COVERAGE_FLAG="-DCOVERAGE_FLAG=-coverage"
        - SONARCLOUD_ENABLED
      addons:
        sonarcloud:
          organization: "mualphaomegaepsilon-github"

    - os: osx

    - os: windows

script:
  - if [ ! -z "${COVERAGE_FLAG:-}" ]; then sudo rm /usr/bin/gcov && ln -s /usr/bin/gcov-5 /usr/bin/gcov; fi
  - shellcheck tests/setup.sh && ./tests/setup.sh
  - shellcheck tests/build.sh && ./tests/build.sh
  - shellcheck tests/run.sh && ./tests/run.sh
  - if [! -z "${SONARCLOUD_ENABLED:-}" ]; then sonar-scanner; fi
  - if [ ! -z "${COVERAGE_FLAG:-}" ]; then bash <(curl -s https://codecov.io/bash); fi
