language: cpp

matrix:
  include:

    - os: linux
      compiler: clang

    - os: linux
      compiler: g++
      addons:
        apt:
          sources: 'ubuntu-toolchain-r-test'
          packages: g++-8
      env: RELINK_GCC=true

    - os: osx

    - os: windows

script:
  - if [[ "$RELINK_GCC" ]]; then sudo rm /usr/bin/g++; fi
  - if [[ "$RELINK_GCC" ]]; then sudo ln -s /usr/bin/g++-8 /usr/bin/g++; fi
  - ./tests/run.sh