language: cpp

dist: xenial

matrix:
  include:

    - os: linux
      compiler: clang  

    - os: linux
      compiler: g++
      env: 
        - COVERAGE_FLAG="-DCOVERAGE_FLAG=-coverage"
        - SONARCLOUD_ENABLED
      addons:
        sonarcloud:
          organization: "mualphaomegaepsilon-github"

    - os: osx

    - os: windows

jobs:
  include:

    - stage: test
      script: if [ ! -z "${COVERAGE_FLAG:-}" ]; then sudo rm /usr/bin/gcov && ln -s /usr/bin/gcov-5 /usr/bin/gcov; fi
      script: ./tests/setup.sh
      script: ./tests/build.sh
      script: ./tests/run.sh
      script: if [! -z "${SONARCLOUD_ENABLED}" ]; then sonar-scanner; fi
      script: if [ ! -z "${COVERAGE_FLAG:-}" ]; then bash <(curl -s https://codecov.io/bash); fi
