language: cpp

dist: xenial
sudo: false

matrix:
  include:

    - os: linux
      compiler: clang  

    - os: linux
      compiler: g++
      env: 
        - CODECOV_TOKEN="785031cb-d414-4550-8c86-ae4bf6ecd5b4"
        - SONAR_SCANNER="true"
      addons:
        sonarcloud:
          organization: "mualphaomegaepsilon-github"

    - os: osx

    - os: windows

script:
  - if [ ! -z "${CODECOV_TOKEN:-}" ]; then sudo rm /usr/bin/gcov; fi
  - if [ ! -z "${CODECOV_TOKEN:-}" ]; then sudo ln -s /usr/bin/gcov-5 /usr/bin/gcov; fi
  - if [ ! -z "${SONAR_SCANNER:-}" ]; then cmake . -DBUILD_TESTING=ON; fi
  - if [ ! -z "${SONAR_SCANNER:-}" ]; then build-wrapper-linux-x86-64 --out-dir bw-output make all; fi
  - if [ ! -z "${SONAR_SCANNER:-}" ]; then make test; fi
  - if [ ! -z "${SONAR_SCANNER:-}" ]; then sonar-scanner -X; fi
  - ./tests/run.sh
