language: cpp

dist: xenial
sudo: false

matrix:
  include:

    - os: linux
      compiler: clang  

    - os: linux
      compiler: g++
      env: CODECOV_TOKEN="785031cb-d414-4550-8c86-ae4bf6ecd5b4"

    - os: osx

    - os: windows

script:
  - if [ ! -z "${CODECOV_TOKEN:-}" ]; then sudo rm /usr/bin/gcov; fi
  - if [ ! -z "${CODECOV_TOKEN:-}" ]; then sudo ln -s /usr/bin/gcov-5 /usr/bin/gcov; fi
  - ./tests/run.sh